[package]
name = "desktop"
version = "0.1.0"
description = "Turms app."
edition = "2024"

[lib]
name = "desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true

[profile.release.package.libturms]
opt-level = 3

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
chrono = { version = "0", features = ["serde"] }
anyhow = "1"
url = "2.5"

window-vibrancy = "0.6"
tauri-plugin-fs = "2.4.2"
tauri-plugin-notification = "2.3.1"
tauri-plugin-shell = "2"
tauri-plugin-http = "2.5.2"
tauri-plugin-dialog = "2.4.0"
tauri-plugin-opener = "2"
tauri-plugin-deep-link = "2"

# Related to database.
rusqlite = { version = "0.37.0", features = ["bundled-sqlcipher"] }
rand = "0.9"
rand_chacha = "0.9.0"
hex = "0.4"
chacha20poly1305 = { version = "0.10", features = ["std"] } # encryption at rest.
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] } # save local keys.

# Related to telecommunication.
libturms = { git = "https://github.com/TurmsApp/libturms" }
tauri-plugin-process = "2"
tauri-plugin-log = "2"

[target."cfg(any(target_os = \"macos\", windows, target_os = \"linux\"))".dependencies]
tauri-plugin-single-instance = { version = "2.0.0", features = ["deep-link"] }
